version: '3'

networks:
  inside_net:
    name: inside_net

services:
  nginx:
    image: nginx:1.25.3
    networks:
      - inside_net
    depends_on:
      - app1
    ports:
      - '${APP_PORT}:${APP_PORT}'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./default.conf.template:/etc/nginx/templates/default.conf.template
    environment:
      - 'APP_PORT=${APP_PORT}'
      - 'APP1_HOST=${APP1_HOST}'
      - 'APP2_HOST=${APP2_HOST}'
      - 'APP3_HOST=${APP3_HOST}'
      - 'APP4_HOST=${APP4_HOST}'
      - 'APP5_HOST=${APP5_HOST}'

  app1:
    build: .
    networks:
      - inside_net
    depends_on:
      - postgres_db
    environment:
       - 'DB_HOST=postgres_db'

  app2:
    build: .
    networks:
      - inside_net
    depends_on:
      - postgres_db
    environment:
       - 'DB_HOST=postgres_db'

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 8080:8080
    environment: 
      - 'ADMINER_DEFAULT_SERVER=postgres_db:5432'
    networks: 
      - inside_net

  postgres_db: 
    image: postgres
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    networks: 
      - inside_net
    environment:
      POSTGRES_USER: '${DB_USER}'
      POSTGRES_PASSWORD: '${DB_PASSWORD}'
      POSTGRES_DB: '${DB_NAME}'

