version: '3'
name: test_task

networks:
  inside_net:
    name: inside_net

services:
  nginx:
    image: nginx:1.25.3
    depends_on:
      - app1
      - app2
      - app3
      - app4
      - app5
    networks:
      - inside_net
    ports:
      - '${APP_PORT}:${APP_PORT}'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./default.conf.template:/etc/nginx/templates/default.conf.template
    environment:
      - 'APP_PORT=${APP_PORT}'
      - 'APP1_HOST=${APP1_HOST}'
      - 'APP2_HOST=${APP2_HOST}'
      - 'APP3_HOST=${APP3_HOST}'
      - 'APP4_HOST=${APP4_HOST}'
      - 'APP5_HOST=${APP5_HOST}'

  app1:
    image: test_task-app
    networks:
      - inside_net
    depends_on:
      - postgres_db
    environment:
       - 'DB_HOST=postgres_db'
       - 'DOCKER_CONTAINER_APP_HOST=${APP1_HOST}'

  app2:
    image: test_task-app
    networks:
      - inside_net
    depends_on:
      - postgres_db
    environment:
       - 'DB_HOST=postgres_db'
       - 'DOCKER_CONTAINER_APP_HOST=${APP2_HOST}'

  app3:
    image: test_task-app
    networks:
      - inside_net
    depends_on:
      - postgres_db
    environment:
       - 'DB_HOST=postgres_db'
       - 'DOCKER_CONTAINER_APP_HOST=${APP3_HOST}'

  app4:
    image: test_task-app
    networks:
      - inside_net
    depends_on:
      - postgres_db
    environment:
       - 'DB_HOST=postgres_db'
       - 'DOCKER_CONTAINER_APP_HOST=${APP4_HOST}'

  app5:
    image: test_task-app
    networks:
      - inside_net
    depends_on:
      - postgres_db
    environment:
       - 'DB_HOST=postgres_db'
       - 'DOCKER_CONTAINER_APP_HOST=${APP5_HOST}'

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 8080:8080
    environment: 
      - 'ADMINER_DEFAULT_SERVER=postgres_db:5432'
    networks: 
      - inside_net

  postgres_db: 
    image: postgres
    networks: 
      - inside_net
    environment:
      POSTGRES_USER: '${DB_USER}'
      POSTGRES_PASSWORD: '${DB_PASSWORD}'
      POSTGRES_DB: '${DB_NAME}'

